export const fieldLabels: Record<string, string> = {
  code: '코드',
  name: '이름',
  ceo: '대표자',
  bizNo: '사업자번호',
  manager: '담당자',
  phone: '연락처',
  status: '상태',
  lastDate: '최근 처리일',
  amount: '금액',
  spec: '규격',
  unit: '단위',
  purchase: '매입 단가',
  sales: '판매 단가',
  owner: '담당자',
  item: '품목',
  warehouse: '창고',
  current: '현재고',
  reserved: '예약재고',
  reservedQty: '예약 수량',
  safety: '안전재고',
  available: '가용재고',
  no: '문서 번호',
  customer: '거래처',
  vendor: '매입처',
  orderDate: '작성일',
  dueDate: '납기일',
  received: '입고 여부',
  receivedDate: '입고일',
  shipped: '출고 여부',
  shippedDate: '출고일',
  issued: '투입 여부',
  issueDate: '투입일',
  productionReceived: '생산 입고 여부',
  productionReceivedDate: '생산 입고일',
  sourceOrder: '원천 수주',
  line: '라인',
  start: '시작일',
  end: '종료일',
  qty: '수량',
  progress: '진행률',
  id: '사용자 ID',
  dept: '부서',
  role: '역할',
  auth: '권한'
}

export function fieldLabel(key: string) {
  return fieldLabels[key] || key
}
